import fs from 'fs';
import path from 'path';
import { RallyClient } from '../core/rally-client.js';

export interface IGeneratorOptions {
    apiKey: string;
    workspaceId: string;
    outputDir: string;
    baseImport?: string;
    /** If provided, only generate models whose ElementName is in this list. */
    include?: string[];
}

/** AttributeTypes that map to a scalar/string TS value (not relations). */
const STRING_LIKE_TYPES = new Set(['STRING', 'TEXT', 'STATE', 'RATING', 'RAW']);

/** AttributeTypes for which AllowedValues contain meaningful string enum literals. */
const ENUM_ELIGIBLE_TYPES = new Set(['STRING', 'STATE', 'RATING']);

function mapAttributeType(attrType: string): string {
    if (attrType === 'INTEGER') return "'integer'";
    if (attrType === 'QUANTITY' || attrType === 'DECIMAL') return "'number'";
    if (attrType === 'BOOLEAN') return "'boolean'";
    if (attrType === 'DATE') return "'date'";
    return "'string'"; // STRING, TEXT, STATE, RATING, RAW
}

export async function generateModels(options: IGeneratorOptions): Promise<void> {
    const { apiKey, workspaceId, outputDir } = options;

    const client = new RallyClient({
        apiKey,
        workspace: workspaceId.startsWith('/workspace/') ? workspaceId : `/workspace/${workspaceId}`,
        logger: {
            debug: () => {},
            info: (msg) => console.log(`   ${msg}`),
            warn: (msg) => console.warn(`   WARN: ${msg}`),
            error: (msg) => console.error(`   ERROR: ${msg}`)
        }
    });

    console.log('Fetching TypeDefinitions from Rally...');

    const types = await client.queryAll('TypeDefinition', {
        fetch: 'ObjectID,Name,ElementName,TypePath,Attributes,Abstract,Parent',
        pagesize: 200
    });

    let validTypes = types.filter((t: any) => t.ElementName && t.Abstract === false);

    if (options.include && options.include.length > 0) {
        const includeSet = new Set(options.include.map(n => n.toLowerCase()));
        validTypes = validTypes.filter((t: any) =>
            includeSet.has((t.ElementName as string).toLowerCase())
        );
    }

    console.log(`Found ${validTypes.length} valid TypeDefinitions. Gathering attributes...`);

    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    const classNames: string[] = [];
    const seenClassNames = new Set<string>();

    for (let i = 0; i < validTypes.length; i++) {
        const typeDef = validTypes[i] as any;
        const className = sanitizeClassName(typeDef.ElementName || typeDef.Name);
        console.log(`[${i + 1}/${validTypes.length}] Generating ${className}...`);

        let attributesResponse: any[] = [];
        if (typeDef.Attributes && typeDef.Attributes._ref) {
            try {
                attributesResponse = await client.queryCollectionAll(typeDef.Attributes._ref, {
                    fetch: 'ElementName,Name,AttributeType,Required,Hidden,Custom,AllowedValueType,MaxLength,ReadOnly,Constrained,MaxFractionalDigits,Filterable,Sortable,AllowedValues',
                    pagesize: 200
                });
            } catch (err: any) {
                console.warn(`   Could not load attributes for ${className}: ${err.message}`);
            }
        }

        // Fetch AllowedValues in parallel for constrained string/state/rating fields
        const enumMap = await fetchEnumValues(client, attributesResponse);

        const fileName = `${className.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()}.ts`;
        const filePath = path.join(outputDir, fileName);

        const classContent = generateClassContent(className, typeDef, attributesResponse, enumMap, options.baseImport);
        fs.writeFileSync(filePath, classContent, 'utf-8');

        if (!seenClassNames.has(className)) {
            seenClassNames.add(className);
            classNames.push(className);
        }
    }

    const imports = classNames.map(cn => `import { ${cn} } from './${cn.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()}.js';`).join('\n');
    const exportNames = classNames.join(',\n    ');
    const indexContent =
        `// Automatically generated by RallyORM CLI\n` +
        imports + '\n\n' +
        `export {\n    ${exportNames}\n};\n\n` +
        `export const GENERATED_MODELS = [\n${classNames.map(cn => `    ${cn}`).join(',\n')}\n];\n`;

    fs.writeFileSync(path.join(outputDir, 'index.ts'), indexContent, 'utf-8');
}

/**
 * For each attribute that is a constrained STRING/STATE/RATING with AllowedValues,
 * fetch the actual enum string values in parallel.
 */
async function fetchEnumValues(client: RallyClient, attributes: any[]): Promise<Map<string, string[]>> {
    const eligible = attributes.filter(
        attr =>
            attr.Constrained &&
            ENUM_ELIGIBLE_TYPES.has(attr.AttributeType) &&
            attr.AllowedValues?._ref &&
            attr.AllowedValues?.Count > 0
    );

    if (eligible.length === 0) return new Map();

    const results = await Promise.all(
        eligible.map(async attr => {
            try {
                const avItems = await client.queryCollectionAll(attr.AllowedValues._ref, {
                    fetch: 'StringValue',
                    pagesize: 200
                });
                const values = avItems
                    .map((v: any) => v.StringValue)
                    .filter((v: any) => v !== null && v !== undefined && v !== '');
                return { elementName: attr.ElementName, values };
            } catch {
                return { elementName: attr.ElementName, values: [] };
            }
        })
    );

    return new Map(results.filter(r => r.values.length > 0).map(r => [r.elementName, r.values]));
}

function sanitizeClassName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '');
}

function generateClassContent(
    className: string,
    typeDef: any,
    attributes: any[],
    enumMap: Map<string, string[]>,
    baseImport = 'rallyorm'
): string {
    const entityType = (typeDef.TypePath ?? typeDef.ElementName).toLowerCase();

    let fieldsStr = '';
    let relationsStr = '';

    for (const attr of attributes) {
        const attrName = attr.ElementName;
        const attrType = attr.AttributeType;

        if (attrType === 'OBJECT' || attrType === 'COLLECTION') {
            const relType = attrType === 'OBJECT' ? 'belongsTo' : 'hasMany';
            const relatedEntity = attr.AllowedValueType?._refObjectName
                ? attr.AllowedValueType._refObjectName.replace(/[^a-zA-Z0-9_]/g, '')
                : 'unknown';

            let relMeta = `\n        ${attrName}: {\n            type: '${relType}',\n            entity: '${relatedEntity}',\n            isCollection: ${attrType === 'COLLECTION'}`;
            if (attrType === 'OBJECT') {
                relMeta += `,\n            foreignKey: '${attrName}'`;
            }
            if (attr.ReadOnly) {
                relMeta += `,\n            readOnly: true`;
            }
            relMeta += `\n        },`;
            relationsStr += relMeta;
            continue;
        }

        const mappedType = mapAttributeType(attrType);
        const parts: string[] = [`type: ${mappedType}`];

        if (attr.Required) parts.push('required: true');
        if (attr.ReadOnly) parts.push('readOnly: true');
        if (attr.Hidden) parts.push('hidden: true');
        if (attr.Custom) parts.push('isCustom: true');

        // maxLength: meaningful for string-like types when MaxLength > 0
        if (STRING_LIKE_TYPES.has(attrType) && attr.MaxLength > 0) {
            parts.push(`maxLength: ${attr.MaxLength}`);
        }

        // enum values for constrained string/state/rating fields
        const enumValues = enumMap.get(attrName);
        if (enumValues && enumValues.length > 0) {
            const quoted = enumValues.map(v => `'${v.replace(/'/g, "\\'")}'`).join(', ');
            parts.push(`enum: [${quoted}]`);
        }

        // maxFractionalDigits for QUANTITY fields (omit when -1 = unlimited)
        if (attrType === 'QUANTITY' && attr.MaxFractionalDigits !== undefined && attr.MaxFractionalDigits >= 0) {
            parts.push(`maxFractionalDigits: ${attr.MaxFractionalDigits}`);
        }

        // filterable / sortable: only emit when explicitly false (true is the normal default)
        if (attr.Filterable === false) parts.push('filterable: false');
        if (attr.Sortable === false) parts.push('sortable: false');

        fieldsStr += `\n        ${attrName}: { ${parts.join(', ')} },`;
    }

    return `import { RallyEntity } from '${baseImport}';

/**
 * Generated model for ${typeDef.Name}
 */
export class ${className} extends RallyEntity {
    static override readonly entityType = '${entityType}';

    static override readonly fields = {${fieldsStr}
    };

    static override readonly relations = {${relationsStr}
    };
}
`;
}
