// Automatically generated by RallyORM CLI
import { Attachment } from './attachment.js';
import { Defect } from './defect.js';
import { Feature } from './feature.js';
import { HierarchicalRequirement } from './hierarchical-requirement.js';
import { Initiative } from './initiative.js';
import { Iteration } from './iteration.js';
import { Milestone } from './milestone.js';
import { Project } from './project.js';
import { Release } from './release.js';
import { StrategicTheme } from './strategic-theme.js';
import { Tag } from './tag.js';
import { Task } from './task.js';
import { TestCase } from './test-case.js';
import { TestCaseResult } from './test-case-result.js';
import { TestCaseStep } from './test-case-step.js';
import { TestFolder } from './test-folder.js';
import { TestSet } from './test-set.js';
import { User } from './user.js';
import { Workspace } from './workspace.js';
import { WorkspaceConfiguration } from './workspace-configuration.js';

export {
    Attachment,
    Defect,
    Feature,
    HierarchicalRequirement,
    Initiative,
    Iteration,
    Milestone,
    Project,
    Release,
    StrategicTheme,
    Tag,
    Task,
    TestCase,
    TestCaseResult,
    TestCaseStep,
    TestFolder,
    TestSet,
    User,
    Workspace,
    WorkspaceConfiguration
};

export const GENERATED_MODELS = [
    Attachment,
    Defect,
    Feature,
    HierarchicalRequirement,
    Initiative,
    Iteration,
    Milestone,
    Project,
    Release,
    StrategicTheme,
    Tag,
    Task,
    TestCase,
    TestCaseResult,
    TestCaseStep,
    TestFolder,
    TestSet,
    User,
    Workspace
];
